[phases.setup]
# Indique à Nixpacks d’installer Python 3, pip et les libs nécessaires à OpenCV
nixPkgs = ["python3", "libglvnd"]
aptPkgs = ["libgl1", "libglib2.0-0"]

[phases.install]
cmds = [
  "python3 -m venv venv",
  ". venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'build done'"]

[start]
cmd = ". venv/bin/activate && python app.py"
